const { renderPage } = require('../ui/globals')
const content = require('../ui/page-content/me')
const { fetchUser } = require('logic/getUser')
const { getDecks } = require('logic/decks')
renderPage(content)
;(async () => {
  const [user, decks] = await Promise.all([fetchUser(), getDecks()])
  window.lc.setData('user', user)
  window.lc.setData('decks', decks)
})()
